name: Deploy Website via FTP

on:
  push:
    branches:
      - main # Change this to master if your default branch is named 'master'

jobs:
  web-deploy:
    name: 🎉 Deploy Website
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # Optional: If you want to deploy to a specific directory like public_html
        # server-dir: ./public_html/
        # Optional: If you want to exclude specific files from being uploaded
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          Dockerfile
          docker-compose.yml
          .github/**
